// ISO-3166-alpha-2 → continent code. Imported by the map filter UI and the
// server's breakdown endpoint (via a JS-only build that re-exports the map).

export type ContinentCode = "AF" | "AS" | "EU" | "NA" | "OC" | "SA";

const CONTINENT_OF: Record<string, ContinentCode> = {
  // Africa
  AO: "AF",
  BF: "AF",
  BI: "AF",
  BJ: "AF",
  BW: "AF",
  CD: "AF",
  CF: "AF",
  CG: "AF",
  CI: "AF",
  CM: "AF",
  CV: "AF",
  DJ: "AF",
  DZ: "AF",
  EG: "AF",
  EH: "AF",
  ER: "AF",
  ET: "AF",
  GA: "AF",
  GH: "AF",
  GM: "AF",
  GN: "AF",
  GQ: "AF",
  GW: "AF",
  KE: "AF",
  KM: "AF",
  LR: "AF",
  LS: "AF",
  LY: "AF",
  MA: "AF",
  MG: "AF",
  ML: "AF",
  MR: "AF",
  MU: "AF",
  MW: "AF",
  MZ: "AF",
  NA: "AF",
  NE: "AF",
  NG: "AF",
  RE: "AF",
  RW: "AF",
  SC: "AF",
  SD: "AF",
  SH: "AF",
  SL: "AF",
  SN: "AF",
  SO: "AF",
  SS: "AF",
  ST: "AF",
  SZ: "AF",
  TD: "AF",
  TG: "AF",
  TN: "AF",
  TZ: "AF",
  UG: "AF",
  YT: "AF",
  ZA: "AF",
  ZM: "AF",
  ZW: "AF",

  // Asia
  AE: "AS",
  AF: "AS",
  AM: "AS",
  AZ: "AS",
  BD: "AS",
  BH: "AS",
  BN: "AS",
  BT: "AS",
  CC: "AS",
  CN: "AS",
  CX: "AS",
  CY: "AS",
  GE: "AS",
  HK: "AS",
  ID: "AS",
  IL: "AS",
  IN: "AS",
  IO: "AS",
  IQ: "AS",
  IR: "AS",
  JO: "AS",
  JP: "AS",
  KG: "AS",
  KH: "AS",
  KP: "AS",
  KR: "AS",
  KW: "AS",
  KZ: "AS",
  LA: "AS",
  LB: "AS",
  LK: "AS",
  MM: "AS",
  MN: "AS",
  MO: "AS",
  MV: "AS",
  MY: "AS",
  NP: "AS",
  OM: "AS",
  PH: "AS",
  PK: "AS",
  PS: "AS",
  QA: "AS",
  SA: "AS",
  SG: "AS",
  SY: "AS",
  TH: "AS",
  TJ: "AS",
  TL: "AS",
  TM: "AS",
  TR: "AS",
  TW: "AS",
  UZ: "AS",
  VN: "AS",
  YE: "AS",

  // Europe
  AD: "EU",
  AL: "EU",
  AT: "EU",
  AX: "EU",
  BA: "EU",
  BE: "EU",
  BG: "EU",
  BY: "EU",
  CH: "EU",
  CZ: "EU",
  DE: "EU",
  DK: "EU",
  EE: "EU",
  ES: "EU",
  FI: "EU",
  FO: "EU",
  FR: "EU",
  GB: "EU",
  GG: "EU",
  GI: "EU",
  GR: "EU",
  HR: "EU",
  HU: "EU",
  IE: "EU",
  IM: "EU",
  IS: "EU",
  IT: "EU",
  JE: "EU",
  LI: "EU",
  LT: "EU",
  LU: "EU",
  LV: "EU",
  MC: "EU",
  MD: "EU",
  ME: "EU",
  MK: "EU",
  MT: "EU",
  NL: "EU",
  NO: "EU",
  PL: "EU",
  PT: "EU",
  RO: "EU",
  RS: "EU",
  RU: "EU",
  SE: "EU",
  SI: "EU",
  SJ: "EU",
  SK: "EU",
  SM: "EU",
  UA: "EU",
  VA: "EU",
  XK: "EU",

  // North America
  AG: "NA",
  AI: "NA",
  AW: "NA",
  BB: "NA",
  BL: "NA",
  BM: "NA",
  BQ: "NA",
  BS: "NA",
  BZ: "NA",
  CA: "NA",
  CR: "NA",
  CU: "NA",
  CW: "NA",
  DM: "NA",
  DO: "NA",
  GD: "NA",
  GL: "NA",
  GP: "NA",
  GT: "NA",
  HN: "NA",
  HT: "NA",
  JM: "NA",
  KN: "NA",
  KY: "NA",
  LC: "NA",
  MF: "NA",
  MQ: "NA",
  MS: "NA",
  MX: "NA",
  NI: "NA",
  PA: "NA",
  PM: "NA",
  PR: "NA",
  SV: "NA",
  SX: "NA",
  TC: "NA",
  TT: "NA",
  US: "NA",
  VC: "NA",
  VG: "NA",
  VI: "NA",

  // Oceania
  AS: "OC",
  AU: "OC",
  CK: "OC",
  FJ: "OC",
  FM: "OC",
  GU: "OC",
  KI: "OC",
  MH: "OC",
  MP: "OC",
  NC: "OC",
  NF: "OC",
  NR: "OC",
  NU: "OC",
  NZ: "OC",
  PF: "OC",
  PG: "OC",
  PN: "OC",
  PW: "OC",
  SB: "OC",
  TK: "OC",
  TO: "OC",
  TV: "OC",
  UM: "OC",
  VU: "OC",
  WF: "OC",
  WS: "OC",

  // South America
  AR: "SA",
  BO: "SA",
  BR: "SA",
  CL: "SA",
  CO: "SA",
  EC: "SA",
  FK: "SA",
  GF: "SA",
  GY: "SA",
  PE: "SA",
  PY: "SA",
  SR: "SA",
  UY: "SA",
  VE: "SA",
};

export function continentOf(country: string | null | undefined): ContinentCode | null {
  if (!country) return null;
  return CONTINENT_OF[country.toUpperCase()] ?? null;
}

export const CONTINENT_LABEL: Record<ContinentCode, string> = {
  AF: "Africa",
  AS: "Asia",
  EU: "Europe",
  NA: "N. America",
  OC: "Oceania",
  SA: "S. America",
};

// Geographic bounds for each continent. Used by the world map to zoom into
// the active filter region. Format: [minLat, minLon, maxLat, maxLon].
export const CONTINENT_BOUNDS: Record<ContinentCode, [number, number, number, number]> = {
  NA: [7, -168, 72, -52],
  SA: [-56, -82, 13, -34],
  EU: [35, -25, 72, 45],
  AF: [-35, -18, 38, 52],
  AS: [-11, 26, 78, 180],
  OC: [-48, 110, 0, 180],
};

// Curated MVP country set with hand-tuned bounding boxes. We deliberately ship
// 10 countries (one or two per inhabited continent) instead of all 250 so the
// filter UI stays scannable. Format: [minLat, minLon, maxLat, maxLon].
export const COUNTRY_BOUNDS: Record<string, [number, number, number, number]> = {
  US: [24.5, -125, 49.4, -66.9], // continental US
  CA: [42, -141, 70, -52],
  MX: [14.5, -118.4, 32.7, -86.7],
  BR: [-33.7, -73.9, 5.2, -34.7],
  GB: [49.9, -8.7, 60.9, 1.8],
  DE: [47.3, 5.9, 55.1, 15],
  IN: [6.7, 68.1, 35.5, 97.4],
  JP: [30.2, 129, 45.5, 145.8],
  ZA: [-34.8, 16.4, -22.1, 32.9],
  AU: [-43.6, 113, -10.7, 153.6],
};

export interface CuratedCountry {
  code: string;
  name: string;
  flag: string;
  continent: ContinentCode;
}

// The order is the chip render order on the dashboard: roughly geographic
// (west-to-east, north-to-south) so the row reads as a tour of the world.
export const CURATED_COUNTRIES: CuratedCountry[] = [
  { code: "US", name: "United States", flag: "🇺🇸", continent: "NA" },
  { code: "CA", name: "Canada", flag: "🇨🇦", continent: "NA" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", continent: "NA" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", continent: "SA" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", continent: "EU" },
  { code: "DE", name: "Germany", flag: "🇩🇪", continent: "EU" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", continent: "AF" },
  { code: "IN", name: "India", flag: "🇮🇳", continent: "AS" },
  { code: "JP", name: "Japan", flag: "🇯🇵", continent: "AS" },
  { code: "AU", name: "Australia", flag: "🇦🇺", continent: "OC" },
];
